version: '3'
services:
  lanproxy-server:
    build: .
    network_mode: host
    volumes:
      - ./config.properties:/opt/proxy-server-20171116/conf/config.properties
      - ./lanproxy-data:/root/.lanproxy
